### ISSUE TITLE
Noises and high CPU cycles when playing over 1000 voices

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/Keppy-s-Driver#10]
I don't know if this is a bug or not, but when I play a black MIDI that has over 1000 voices in one time, the CPU cycles quickly rise and make noises (no noises with the BASSMIDI driver)

**Comment by KaleidonKep99** [comment]
This happens after a recent update of both BASS and BASSMIDI libraries, I don't think it's driver's fault at all.
I'll look further into this btw.

**Comment by nguyenlong2004** [comment]
Thanks. I will wait.

**Comment by KaleidonKep99** [comment]
So, it happens on BASSMIDI Driver too, after the update?

**Comment by KaleidonKep99** [comment]
Now I understand the problem.
BASSMIDI Driver is actually limited to 256 voices, while on mine you can raise it to max 100.000.
That's why BASSMIDI Driver isn't affected by the problem.

**Comment by nguyenlong2004** [comment]
I use the precompiled version.
PS: I also tried to open that 1000 voices black MIDI and it's doesn't even make noises.

**Comment by KaleidonKep99** [comment]
It doesn't make strange noises because it's limited to 256 voices (Or was it limited to 250? I don't remember).

**Comment by nguyenlong2004** [comment]
Hmm....... I need to investigate that 256 voices limit and why it can play 1000 voices without any voice killing (That's my feeling. You can try that with yourself)

**Comment by KaleidonKep99** [comment]
The new BASSMIDI is still killing voice, but with a fade out of a few milliseconds, avoiding the 

> Here's another BASSMIDI update for you to try:

>	www.un4seen.com/stuff/bassmidi.zip

> When the voice limit (BASS_MIDI_ATTRIB_VOICES) is hit, it will temporarily raise the limit to fade-out the killed voices (rather than stopping them abruptly), to avoid click noises. That should especially help the sound quality of black MIDI files, as they constantly hit the voice limit. The extra voices does mean it will use a bit more CPU than before when the

**Comment by nguyenlong2004** [comment]
I will try compile BASSMIDI driver myself and see if there anything different (and your driver too!)

**Comment by nguyenlong2004** [comment]
Still messing around with Inno Setup, WDK and Visual Studio :)
PS: This is just some update for you :)

**Comment by nguyenlong2004** [comment]
Can't compile this at all!! Always "Cannot open source file: 'bassmididrv.cpp': No such file or directory"
PS: I'll not gonna blame you or something but why?

**Comment by KaleidonKep99** [comment]
I have to reinstall Visual Studio 2013 to my PC, since I reinstalled Windows 7.
I'll compile a 1000 voices version of BASSMIDI Driver for you.

**Comment by nguyenlong2004** [comment]
Thanks. Glad you're still here with me.
PS: I think that I'm halfway through the compiling. Just need to find some header file :)

**Comment by nguyenlong2004** [comment]
I have a question:
Why the keppydrv.dll made by the compiling process so large (303KB) compare with the precompiled one (about 60KB) ?

**Comment by KaleidonKep99** [comment]
> I have a question:
> Why the keppydrv.dll made by the compiling process so large (303KB) compare with the precompiled one (about 60KB) ?
Try cleaning the project.

**Comment by kode54** [comment]
Possibly a difference in C runtime settings? The choice of static runtime would definitely account for the size difference.

**Comment by KaleidonKep99** [comment]
Try this edited version of BASSMIDI Driver, Nguyen.

https://drive.google.com/file/d/0B05Sp4zxPFR6U3d6bHJNOHYxdTg/view?usp=sharing

**Comment by nguyenlong2004** [comment]
Thanks. I will test it later
PS: I'm Vietnamese so my name is a little weird :D

**Comment by longnguyen2004** [comment]
It works perfectly. Thanks a lot.
PS: BASSMIDI driver seem to behave differently on different machine. On my Core i3, it work perfectly (no noises, even before upgrade). On my Pentium Dual Core, when the voices limit is hit, it mute the sound completely.
PS2: When I try to use the 303KB keppydrv.dll, a Debug Assertion Failed error occurred.

**Comment by KaleidonKep99** [comment]
> It works perfectly. Thanks a lot.
PS: BASSMIDI driver seem to behave differently on different machine. On my Core i3, it work perfectly (no noises, even before upgrade). On my Pentium Dual Core, when the voices limit is hit, it mute the sound completely.

Yea, MIDI performances are hugely affected by the host CPU.

> PS2: When I try to use the 303KB keppydrv.dll, a Debug Assertion Failed error occurred.

You need to compile it for Release, not Debug.
See here: http://prntscr.com/97qufd

**Comment by longnguyen2004** [comment]
Oh. I forgot :)

**Comment by longnguyen2004** [comment]
I think it's BASSMIDI fault, because when I compile the BASSMIDI driver with 100000 voices, it does make noises. I think it's time to close this thread.
PS: BTW, please ask for this problem on the BASS forum for me :)

**Comment by KaleidonKep99** [comment]
I'll talk with Ian Luck about this.
Thanks for the report anyway! :)

(I'll close the thread, there's no need to leave it opened. We'll use e-mail.)

**Comment by longnguyen2004** [comment]
I just created my own thread at the un4seen forum. If you want, go chech it out!
