### ISSUE TITLE
Debug mode doesn't work ALPHA VERSION

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/Keppy-s-Driver#11]
Hi. The debug mode doesn't work in alpha. Nothing to talk anymore?

**Comment by KaleidonKep99** [comment]
I forgot to mention that in the changelog.

**Debug mode has been removed in the ALPHA. It caused the configurator to crash. The keys are still accessible from HKEY_CURRENT_USER/Software/Keppy's Driver, by using regedit.**
