### ISSUE TITLE
SFZ guide give an error

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/Keppy-s-Driver#14]
Like the title says, the SFZ guide give an error when you click on it.
![untitled](https://cloud.githubusercontent.com/assets/15729831/12005860/7ad6a718-abed-11e5-9676-92d8c32311fa.png)

**Comment by KaleidonKep99** [comment]
I'll embed the text file into a messagebox, thanks for the report. :)

**Comment by KaleidonKep99** [comment]
Fixed.
