### ISSUE TITLE
Incomplete text (or something) + suggestion to the blacklist system

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/Keppy-s-Driver#15]
![untitled](https://cloud.githubusercontent.com/assets/15729831/12215905/96ae84d6-b702-11e5-9a5f-d119634873a2.png)
To what?

Also, a little suggestion for the blacklist system:
Can you remove the warning dialog box about the process being blacklisted? I think it's unnecessary. Sometime, it even frozen and can't close.

**Comment by KaleidonKep99** [comment]
Fixed...
