### ISSUE TITLE
Suggestion to the installer

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/Keppy-s-Driver#16]
Can you bundle the Visual C++ Redistributable 2013 with the installer? It will help saves some time. I was really frustrated when PFA doesn't recognize the driver and waste a lot of time reinstalling PFA and the driver only to find out later that I need to install VC++ Redist, so bundle it will help a lot.

**Comment by KaleidonKep99** [comment]
I can't bundle both x32 and x64 installers of VC++ 2013, since they take 30MB of space...
