### ISSUE TITLE
No sflist support

### ISSUE THREAD

**Issue by jimbo1qaz** [KaleidonKep99/Keppy-s-Driver#6]
BASSMIDIdrv supports sflist import (text files containing soundfont paths). This makes it easier to manage collections of soundfonts which can be applied at once. When you add it, the list is cleared and replaced with the contents of the sflist.

Your driver doesn't support loading multiple soundfonts at once, making it very awkward to use.

**Comment by KaleidonKep99** [comment]
Ehm, you're wrong.
My driver DOES support sflist files, since it's a direct fork of BASSMIDI Driver.

**Comment by kode54** [comment]
And the configuration tool is not a direct fork, but a complete rewrite in Visual Basic. Maybe I'll look at that too.

**Comment by kode54** [comment]
Nope, no .sflist importing support. It should directly copy the lines from the .sflist to the configuration. It should not do a binary copy, since the file encoding may be different, or may be preceded by a byte order marker.

**Comment by KaleidonKep99** [comment]
Oh right, I was wrong.

I'll implement it in the next release.

**Comment by KaleidonKep99** [comment]
Added to the 1.5.0.62.
If it doesn't work, please open another issue. 

GL :palm_tree:
